controllers/ItemsController.php
<?php

namespace app\controllers;

use app\components\utils\LassiDAOUtils;
use app\components\utils\UserDetails;
use app\models\ItemCategoriesModel;
use Yii;
use app\models\ItemDetailsModel;
use app\models\ItemDetailsSearch;
use app\models\ItemStoreMappingModel;
use app\models\ItemSubCategoriesModel;
use app\models\MasterItemDetails;
use app\models\MasterItemDetailsModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ItemsController implements the CRUD actions for ItemDetailsModel model.
 */
class ItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ItemDetailsModel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $storeId = UserDetails::get_restaurant_id();

        $storeMappings = ItemStoreMappingModel::find(['primary_category_id'])->where(['store_id' => $storeId])->all();

        $primaryCategoryIds = array_column($storeMappings, "primary_category_id");

        $itemCategories = ItemCategoriesModel::find()->where(['category_id' => $primaryCategoryIds])->all();

        return $this->render('index', [
            'model' => $itemCategories,
        ]);

    }//end func


    /**
     * 
     * @return mixed
     */
    public function actionViewSubCats($categoryId)
    {

        $subCategories = ItemSubCategoriesModel::find()->where(['primary_category_id' => $categoryId])->all();
        
        return $this->render('sub-cats', [
            'subCats' => $subCategories,
            'categoryId' => $categoryId,
        ]);

    }//end func

    /**
     
     * @return mixed
     */
    public function actionViewItemsBySubCats($subCategoryId, $categoryId)
    {

        $storeMappings = ItemStoreMappingModel::find()->where(['sub_category_id' => $subCategoryId, 'store_id' => UserDetails::get_restaurant_id()])->all();

        $itemIds = array_column($storeMappings, 'item_id');
        
        $masterItems = MasterItemDetails::find()->where(['item_id' => $itemIds])->all();

        $indexedMasterItems = LassiDAOUtils::pivotARObjByIndex($masterItems, 'item_id');

        return $this->render('list-items', [
            'storeItems' => $storeMappings,
            'masterItems' => $indexedMasterItems,
            'subCategoryId' => $subCategoryId,
            'categoryId' => $categoryId,
        ]);

    }//end func




    /**
     * Displays a single ItemDetailsModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ItemDetailsModel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ItemDetailsModel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->item_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ItemDetailsModel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($itemId, $itemStoreId)
    {
        $model = ItemStoreMappingModel::findOne($itemStoreId);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //save also the values updated in Master Item Details
            $postParams = Yii::$app->request->post();

            //get the Master Items isVeg post param value
            $isVeg = $postParams['MasterItemDetails']['is_veg'];

            $itemName = $postParams['MasterItemDetails']['item_name'];

            $masterItem = MasterItemDetails::findOne($model->item_id);

            $masterItem->is_veg = $isVeg;

            $masterItem->item_name = $itemName;

            $masterItem->save(false);

            return $this->redirect(['view-items-by-sub-cats', 'categoryId'=> $model->primary_category_id, 'subCategoryId' => $model->sub_category_id]);
        }

        $masterItem = MasterItemDetails::findOne($itemId);

        return $this->render('update', [
            'model' => $model,
            'masterItem' => $masterItem,
        ]);
    }

    /**
     * Deletes an existing ItemDetailsModel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ItemDetailsModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ItemDetailsModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ItemStoreMappingModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/OrdersController.php
<?php

namespace app\controllers;

use Yii;

use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use app\components\utils\UserDetails;
use  app\components\types\OrderStatusEnum;
use app\models\CustomerOrdersModel;
use app\models\OrderItemsModel;

/**
 * OrdersController implements the CRUD actions for CustomerOrdersModel model.
 */
class OrdersController extends Controller
{
    

    /**
     * Lists all CustomerOrdersModel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $storeId = UserDetails::get_restaurant_id();

        $paymentCompletedOrders = CustomerOrdersModel::find()
                            ->where([
                                'order_status' => OrderStatusEnum::PAYMENT_COMPLETED, 
                                'restaurant_id' => $storeId,
                                ])
                            ->limit(20)
                            ->orderBy(['create_date' => SORT_ASC])
                            ->all();

        return $this->render('index', [
            'paymentCompletedOrders' => $paymentCompletedOrders,
        ]);
    }//end func


    public function actionAcceptedOrders(){
        $storeId = UserDetails::get_restaurant_id();

        $acceptedOrders = CustomerOrdersModel::find()
                        ->where([
                            'order_status' => OrderStatusEnum::RESTAURANT_CONFIRMED, 
                            'restaurant_id' => $storeId,
                            ])
                        ->limit(20)
                        ->orderBy(['create_date' => SORT_ASC])
                        ->all();
        
        return $this->render('accepted-orders', [
            'acceptedOrders' => $acceptedOrders,
        ]);


    }//end func


    public function actionReadyOrders () {
        $storeId = UserDetails::get_restaurant_id();

        $readyOrders = CustomerOrdersModel::find()
                    ->where([
                        'order_status' => OrderStatusEnum::PENDING_PICKUP, 
                        'restaurant_id' => $storeId,
                        ])
                    ->limit(20)
                    ->orderBy(['create_date' => SORT_ASC])
                    ->all();


        return $this->render('ready-orders', [
            'readyOrders' => $readyOrders,
        ]);


    }//end func

    /**
     * Displays a single CustomerOrdersModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {


        $orderItems = new ActiveDataProvider ([
            'query' => OrderItemsModel::find()
                            ->where(['order_id' => $id]),
                'pagination' => [
                    'pageSize' => 30,
                ],
                'sort' => [
                            'defaultOrder' =>  [
                                'last_modified_date' => SORT_DESC,
                            ],
                        ],
            ]);


        return $this->render('view', [
            'model' => $this->findModel($id),
            'orderItems' => $orderItems,
        ]);
    } //end func

    /**
     * Finds the CustomerOrdersModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CustomerOrdersModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CustomerOrdersModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    /**
     * 
     */
    public function actionAcceptOrder($orderId) {

        if (empty($orderId)) {
            //bad request. nothing to process. redirect to orders page
            Yii::$app->session->setFlash('error', "There was an Error. No Order Id passed. Please try again");
            return $this->redirect(['index']);
        }

        //update order status to "restaurant confirmed"
        $response = CustomerOrdersModel::updateOrderStatusByOrderId($orderId, OrderStatusEnum::RESTAURANT_CONFIRMED);

        if (!$response){
            Yii::$app->session->setFlash('error', "Error Updating Status. Please try again ");
            return $this->redirect(['view',
                'id' => $orderId,
            ]);
        }

        Yii::$app->session->setFlash('success', "Order: $orderId - accepted successfully ");
        return $this->redirect(['index']);
    
    
    }//end func

    /**
     * 
     */
    public function actionMarkReady($orderId) {

        if (empty($orderId)) {
            //bad request. nothing to process. redirect to orders page
            Yii::$app->session->setFlash('error', "There was an Error. No Order Id passed. Please try again");
            return $this->redirect(['index']);
        }

        //update order status to "restaurant confirmed"
        $response = CustomerOrdersModel::updateOrderStatusByOrderId($orderId, OrderStatusEnum::PENDING_PICKUP);

        if (!$response){
            Yii::$app->session->setFlash('error', "Error Updating Status. Please try again ");
            return $this->redirect(['view',
                'id' => $orderId,
            ]);
        }

        Yii::$app->session->setFlash('success', "Order: $orderId - accepted successfully ");
        return $this->redirect(['accepted-orders']);
    
    
    }//end func

     /**
     * 
     */
    public function actionMarkDelivered($orderId) {

        if (empty($orderId)) {
            //bad request. nothing to process. redirect to orders page
            Yii::$app->session->setFlash('error', "There was an Error. No Order Id passed. Please try again");
            return $this->redirect(['index']);
        }

        //update order status to "restaurant confirmed"
        $response = CustomerOrdersModel::updateOrderStatusByOrderId($orderId, OrderStatusEnum::ORDER_DELIVERED);

        if (!$response){
            Yii::$app->session->setFlash('error', "Error Updating Status. Please try again ");
            return $this->redirect(['view',
                'id' => $orderId,
            ]);
        }

        Yii::$app->session->setFlash('success', "Order: $orderId - accepted successfully ");
        return $this->redirect(['ready-orders']);
    
    
    }//end func

     /**
     * 
     */
    public function actionRejectOrder($orderId) {

        if (empty($orderId)) {
            //bad request. nothing to process. redirect to orders page
            Yii::$app->session->setFlash('error', "There was an Error. No Order Id passed. Please try again");
            return $this->redirect(['index']);
        }

        //update order status to "restaurant confirmed"
        $response = CustomerOrdersModel::updateOrderStatusByOrderId($orderId, OrderStatusEnum::ORDER_DECLINED_BY_RESTAURANT);

        if (!$response){
            Yii::$app->session->setFlash('error', "Error Updating Status. Please try again ");
            return $this->redirect(['view',
                'id' => $orderId,
            ]);
        }

        Yii::$app->session->setFlash('success', "Order: $orderId - Declined / Cancelled Ssuccessfully ");
        return $this->redirect(['index']);
    
    
    }//end func

    

}

views/layouts/content.php
<?php
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

views/layouts/header.php
<?php
use yii\helpers\Html;
use app\components\utils\UserDetails;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

$ordersBG = '';
$itemsBG = '';
$storeBG = '';

if (Yii::$app->controller->id == "orders"){
    $ordersBG = "cadetblue";
}

if (Yii::$app->controller->id == "items"){
    $itemsBG = "cadetblue";
}

if (Yii::$app->controller->id == "store"){
    $storeBG = "cadetblue";
}

?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">
            <img src="'.\Yii::$app->request->BaseUrl .'/img/PickytoPartnerApp-Logo.jpg" class="img-bordered"  alt="Logo Image"/></span>
            <span class="logo-lg"><img src="'.\Yii::$app->request->BaseUrl .'/img/PickytoPartnerApp-Logo.jpg" class="img-bordered"  alt="Logo Image"/></span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav" style="font-style: 18px; font-weight: bolder; width: 100%; margin-right: 10%;">

                <li class="font-weight-bolder" style="background-color: <?= $ordersBG ?>" >
                <a class="nav-link" href="<?= Url::toRoute(['orders/index']) ?>">
                    <i class="fa fa-arrow-circle-right"></i>
                    Orders
                 </a>
                </li>

                <li class="font-weight-bolder" style="background-color: <?= $itemsBG ?>">
                <a class="nav-link" href="<?= Url::toRoute(['items/index']) ?>">
                    <i class="fa fa-arrow-circle-right"></i>
                    Items
                 </a>
                </li>

                
                <li class="font-weight-bolder" style="background-color: <?= $storeBG ?>">
                <a class="nav-link" href="<?= Url::toRoute([
                                            'store/view', 
                                            'id' => UserDetails::get_restaurant_id(),
                                            ])
                                        ?> 
                                        ">
                    <i class="fa fa-arrow-circle-right"></i>
                    Store
                 </a>
                </li>

                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $directoryAsset ?>/img/avatar5.png" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= Yii::$app->user->identity->getFullName() ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $directoryAsset ?>/img/avatar5.png" class="img-circle"
                                 alt="User Image"/>

                            <p>
                            <?= Yii::$app->user->identity->getFullName() ?>
                            <small>Pickyto Preferred Partner</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Account</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Settings</a>
                            </div>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            
                            <div class="pull-right">
                                <?= Html::a(
                                    'Sign out',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>

views/layouts/left.php
<?php

use app\components\utils\UserDetails;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<aside class="main-sidebar">

    <section class="sidebar">
        
    </section>

</aside>

views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\helpers\Url;;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#ffffff">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>

   
    <link rel="apple-touch-icon" sizes="57x57" href="<?= Url::to('@web/img/apple-icon-57x57.png') ?> ">
    <link rel="apple-touch-icon" sizes="60x60" href="<?= Url::to('@web/img/apple-icon-60x60.png') ?> ">
    <link rel="apple-touch-icon" sizes="72x72" href="<?= Url::to('@web/img/apple-icon-72x72.png') ?> ">
    <link rel="apple-touch-icon" sizes="120x120" href="<?= Url::to('@web/img/apple-icon-120x120.png') ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= Url::to('@web/img/apple-icon-144x144.png') ?>">
    <link rel="apple-touch-icon" sizes="144x144" href="<?= Url::to('@web/img/apple-icon-180x180.png') ?>">


    <link rel="icon" type="image/png" sizes="36x36"  href="<?= Url::to('@web/img/android-icon-36x36.png') ?> ">
    <link rel="icon" type="image/png" sizes="48x48"  href="<?= Url::to('@web/img/android-icon-48x48.png') ?> ">
    <link rel="icon" type="image/png" sizes="72x72"  href="<?= Url::to('@web/img/android-icon-72x72.png') ?> ">
    <link rel="icon" type="image/png" sizes="96x96"  href="<?= Url::to('@web/img/android-icon-96x96.png') ?> ">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?= Url::to('@web/img/android-icon-192x192.png') ?> ">


    <link rel="icon" type="image/png" sizes="32x32" href="<?= Url::to('@web/img/favicon-32x32.png') ?> ">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= Url::to('@web/img/favicon-96x96.png') ?> ">
    <link rel="icon" type="image/png" sizes="16x16" href="<?= Url::to('@web/img/favicon-16x16.png') ?> ">

    <link rel="manifest" href="/manifest.json">

    <link rel="icon" type="image/png" sizes="512x512" href="<?= Url::to('@web/img/PartnerAppSplash.png') ?> ">

    <?php $this->head() ?>
</head>
<body class="login-page" style="background-color: peachpuff;">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>

<script>
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register('/js/sw.js').then(() => {
            console.log('Service Worker registered successfully.');
        }).catch(error => {
            console.log('Service Worker registration failed:', error);
        });
    }
</script>

</html>
<?php $this->endPage() ?>

views/layouts/sub-nav.php
<?php
use yii\helpers\Html;
use app\components\utils\UserDetails;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <nav class="navbar navbar-static-top"  style="background-color:cadetblue;" role="navigation">

        <div class="navbar-custom-menu" style="align-items: center;font-weight: bolder; margin-right: 20%; ">

            <ul class="nav navbar-nav">

                <li class="font-weight-bolder">
                <a class="nav-link" href="<?= Url::toRoute(['orders/index']) ?>">
                    <i class="fa fa-arrow-circle-right"></i>
                    Pending
                 </a>
                </li>

                <li class="">
                <a class="nav-link" href="<?= Url::toRoute(['orders/accepted-orders']) ?>">
                    <i class="fa fa-arrow-circle-right"></i>
                    Accepted
                 </a>
                </li>

                
                <li class="">
                    <a class="nav-link" href="<?= Url::toRoute([ 'orders/ready-orders', 'id' => UserDetails::get_restaurant_id()]) ?>" > 
                    <i class="fa fa-arrow-circle-right"></i>
                    
                    Ready
                 </a>
                </li>

            </ul>
        </div>
    </nav>
</header>