controllers/ItemsController.php
<?php

namespace app\controllers;

use app\components\utils\LassiDAOUtils;
use app\components\utils\UserDetails;
use app\models\ItemCategoriesModel;
use Yii;
use app\models\ItemDetailsModel;
use app\models\ItemDetailsSearch;
use app\models\ItemStoreMappingModel;
use app\models\ItemSubCategoriesModel;
use app\models\MasterItemDetails;
use app\models\MasterItemDetailsModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ItemsController implements the CRUD actions for ItemDetailsModel model.
 */
class ItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ItemDetailsModel models.
     * @return mixed
     */
    public function actionIndex()
    {
        $storeId = UserDetails::get_restaurant_id();

        $storeMappings = ItemStoreMappingModel::find(['primary_category_id'])->where(['store_id' => $storeId])->all();

        $primaryCategoryIds = array_column($storeMappings, "primary_category_id");

        $itemCategories = ItemCategoriesModel::find()->where(['category_id' => $primaryCategoryIds])->all();

        return $this->render('index', [
            'model' => $itemCategories,
        ]);

    }//end func


    /**
     * 
     * @return mixed
     */
    public function actionViewSubCats($categoryId)
    {

        $subCategories = ItemSubCategoriesModel::find()->where(['primary_category_id' => $categoryId])->all();
        
        return $this->render('sub-cats', [
            'subCats' => $subCategories,
            'categoryId' => $categoryId,
        ]);

    }//end func

    /**
     
     * @return mixed
     */
    public function actionViewItemsBySubCats($subCategoryId, $categoryId)
    {

        $storeMappings = ItemStoreMappingModel::find()->where(['sub_category_id' => $subCategoryId, 'store_id' => UserDetails::get_restaurant_id()])->all();

        $itemIds = array_column($storeMappings, 'item_id');
        
        $masterItems = MasterItemDetails::find()->where(['item_id' => $itemIds])->all();

        $indexedMasterItems = LassiDAOUtils::pivotARObjByIndex($masterItems, 'item_id');

        return $this->render('list-items', [
            'storeItems' => $storeMappings,
            'masterItems' => $indexedMasterItems,
            'subCategoryId' => $subCategoryId,
            'categoryId' => $categoryId,
        ]);

    }//end func




    /**
     * Displays a single ItemDetailsModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ItemDetailsModel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ItemDetailsModel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->item_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ItemDetailsModel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($itemId, $itemStoreId)
    {
        $model = ItemStoreMappingModel::findOne($itemStoreId);


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //save also the values updated in Master Item Details
            $postParams = Yii::$app->request->post();

            //get the Master Items isVeg post param value
            $isVeg = $postParams['MasterItemDetails']['is_veg'];

            $itemName = $postParams['MasterItemDetails']['item_name'];

            $masterItem = MasterItemDetails::findOne($model->item_id);

            $masterItem->is_veg = $isVeg;

            $masterItem->item_name = $itemName;

            $masterItem->save(false);

            return $this->redirect(['view-items-by-sub-cats', 'categoryId'=> $model->primary_category_id, 'subCategoryId' => $model->sub_category_id]);
        }

        $masterItem = MasterItemDetails::findOne($itemId);

        return $this->render('update', [
            'model' => $model,
            'masterItem' => $masterItem,
        ]);
    }

    /**
     * Deletes an existing ItemDetailsModel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ItemDetailsModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ItemDetailsModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ItemStoreMappingModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/items/_form.php
<?php

use app\components\utils\UserDetails;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemDetailsModel */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-details-model-form">

    <?php $form = ActiveForm::begin(); ?>

   <div class="col">
       <img src="<?= $masterItem->primary_img ?>" width="100px" height="100x" />
       <span class="font-weight-bolder" style="font-size: 18px; font-weight: bolder;"> <?= $masterItem->item_name ?> </span>
    </div>

    <br>

    <hr>   

    <?= $form->field($masterItem, 'item_name')->textInput() ?>
    
    <?= $form->field($model, 'list_price')->textInput() ?>

    <?= $form->field($model, 'sale_price')->textInput() ?>

    <?=
        $form->field($masterItem, 'is_veg')->dropDownList(['Y' => 'Is Veg', 'N' => 'Non-Veg'], ['options' =>  [$masterItem->is_veg => ['selected' => "true"]]
           
        ])
    ?>

    <?=
        $form->field($model, 'item_status')
                                ->dropDownList(['AVAILABLE' => 'AVAILABLE', 'PENDING' => 'PENDING', 'UNAVAILABLE' => 'UNAVAILABLE'], 
                                ['options' =>  [$model->item_status => ['selected' => "true"]]
           
        ])
    ?>
    <?= $form->field($model, 'last_modified_date')->hiddenInput(['value' => time()])->label(false) ?>

    <?= $form->field($model, 'last_updated_by')->hiddenInput(['value' => Yii::$app->user->identity->getId() ])->label(false) ?>

    <br><br>
    
    <div class="form-group">
        <?= Html::submitButton('Save & Update', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ItemDetailsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="item-details-model-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'item_id') ?>

    <?= $form->field($model, 'product_code') ?>

    <?= $form->field($model, 'restaurant_id') ?>

    <?= $form->field($model, 'item_name') ?>

    <?= $form->field($model, 'item_desc') ?>

    <?php // echo $form->field($model, 'primary_img') ?>

    <?php // echo $form->field($model, 'primary_cuisine') ?>

    <?php // echo $form->field($model, 'primary_category') ?>

    <?php // echo $form->field($model, 'sub_category') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'is_tax_inclusive') ?>

    <?php // echo $form->field($model, 'item_parcel_charge') ?>

    <?php // echo $form->field($model, 'is_parcel_tax_applicable') ?>

    <?php // echo $form->field($model, 'item_status') ?>

    <?php // echo $form->field($model, 'is_refill_item') ?>

    <?php // echo $form->field($model, 'is_veg') ?>

    <?php // echo $form->field($model, 'is_customizable') ?>

    <?php // echo $form->field($model, 'is_todays_special') ?>

    <?php // echo $form->field($model, 'serving_time_slots') ?>

    <?php // echo $form->field($model, 'serving_times') ?>

    <?php // echo $form->field($model, 'available_days') ?>

    <?php // echo $form->field($model, 'prep_time') ?>

    <?php // echo $form->field($model, 'item_tax_code') ?>

    <?php // echo $form->field($model, 'printer_config_name') ?>

    <?php // echo $form->field($model, 'img_url_1') ?>

    <?php // echo $form->field($model, 'img_url_2') ?>

    <?php // echo $form->field($model, 'img_url_3') ?>

    <?php // echo $form->field($model, 'tag_1') ?>

    <?php // echo $form->field($model, 'tag_2') ?>

    <?php // echo $form->field($model, 'tag_3') ?>

    <?php // echo $form->field($model, 'item_count') ?>

    <?php // echo $form->field($model, 'alert_threshold') ?>

    <?php // echo $form->field($model, 'meta_data') ?>

    <?php // echo $form->field($model, 'created_date') ?>

    <?php // echo $form->field($model, 'last_modified_date') ?>

    <?php // echo $form->field($model, 'last_updated_by') ?>

    <?php // echo $form->field($model, 'is_website_displayable') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/items/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ItemDetailsModel */

$this->title = 'Create Item Details Model';
$this->params['breadcrumbs'][] = ['label' => 'Item Details Models', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="item-details-model-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/items/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url; 
/* @var $this yii\web\View */
/* @var $searchModel app\models\ItemDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<div class="item-details-model-index">

<div class="container-fluid">
    <div class="row">
        <i class="fa fa-arrow-circle-right"></i>
        <div class="btn btn-md btn-info">            
            <a class="text-black font-weight-bolder"  href="<?= Url::toRoute(['items/index']) ?>" >
                Category
            </a>
        </div>

        <i class="fa fa-arrow-circle-right"></i>

        <div class="btn btn-sm btn-default disabled">      Sub-Category  </div>

        <i class="fa fa-arrow-circle-right"></i>

        <div class="btn btn-sm btn-default disabled"> Items      </div>

    </div>
</div>

<hr>

<div class="container-fluid">
    <div class="row" >
        <?php foreach ($model as $category) { ?>

        
        <div class="col-sm-3">
            <a href="<?= Url::toRoute(['items/view-sub-cats', 'categoryId' => $category->category_id]) ?>" >
            <div class="box btn btn-lg bg-white text-center" style="border: thin dotted black;">
                <div class="box-header">  
                
                    <h3 class=""><?php echo $category->category_name ?></h3>
            
                </div> 
            </div>
            </a>
        </div> <!-- div:col-sm-4 -->

        <?php } ?>

    </div> <!-- div:row -->
</div><!-- div:container -->


</div>

views/items/list-items.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url; 
/* @var $this yii\web\View */
/* @var $searchModel app\models\ItemDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$primaryCategoryid = $_GET['categoryId']

?>
<div class="item-details-model-index">

<div class="container-fluid">
    <div class="row">
        <i class="fa fa-arrow-circle-right"></i>
        <div class="btn btn-md btn-success">            
            <a class="text-black font-weight-bolder"  href="<?= Url::toRoute(['items/index']) ?>" >
                Category
            </a>
        </div>

        <i class="fa fa-arrow-circle-right"></i>

        <div class="btn btn-md btn-success">
            <a class="text-black font-weight-bolder"  href="<?= Url::toRoute(['items/view-sub-cats', 'categoryId' => $primaryCategoryid]) ?>" >
                Sub-Category
            </a>
        </div>

        <i class="fa fa-arrow-circle-right"></i>

        <div class="btn btn-md btn-info">
            <a class="text-black font-weight-bolder"  href="#" >
                Items
            </a>
        </div>

    </div>
</div>

<hr>

<div class="container-fluid">
    <div class="row" >
        <?php foreach ($storeItems as $storeItem) { 
           $boxBorder = "brown";

            if ($storeItem->item_status == "AVAILABLE") {
                $boxBorder = "green";
            }
            
            ?>

        <div class="col-sm-3">
            <a href="<?= Url::toRoute(['items/update', 'itemId' => $storeItem->item_id, 'itemStoreId' => $storeItem->item_store_mapping_id]) ?>" >
            <div class="box btn btn-lg bg-white text-center" style="border: thick solid <?= $boxBorder ?>;">
                <div class="">  
                    <img src="<?= $masterItems[$storeItem->item_id]->primary_img ?>" width="50px" height="50px" />
                    <h3 class="text-white">
                        <?php 
                         $itemName = $masterItems[$storeItem->item_id]->item_name;
                         $price = $storeItem->sale_price;
                         
                         echo $itemName;
                         echo '<br>';
                         echo '<span style="color: brown;">';
                         echo '&#8377;'.$price;
                         echo '</span>';
                         echo '<br>';
                         echo '<small><em>[edit]</em></small>';
                         ?></h3>
            
                </div> 
            </div>
            </a>
        </div> <!-- div:col-sm-4 -->

        <?php } ?>

    </div> <!-- div:row -->
</div><!-- div:container -->


</div>

views/items/sub-cats.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url; 
/* @var $this yii\web\View */
/* @var $searchModel app\models\ItemDetailsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

?>
<div class="item-details-model-index">

<div class="container-fluid">
    <div class="row">
        <i class="fa fa-arrow-circle-right"></i>

        <a class="text-black font-weight-bolder"  href="<?= Url::toRoute(['items/index']) ?>" >
            <div class="btn btn-md btn-success">            
                    Category
            </div>
        </a>

        <i class="fa fa-arrow-circle-right"></i>
        
        <div class="btn btn-md btn-info">    Sub-Category     </div>

        <i class="fa fa-arrow-circle-right"></i>

        <div class="btn btn-sm btn-default disabled">      Items   </div>

    </div>
</div>

<hr>

<div class="container-fluid">
    <div class="row" >
        <?php foreach ($subCats as $subCategory) { ?>

        
        <div class="col-sm-3">
            <a href="<?= Url::toRoute(['items/view-items-by-sub-cats', 'subCategoryId' => $subCategory->sub_category_id, 
                                        'categoryId' => $subCategory->primary_category_id]) ?>" >

            <div class="box btn btn-lg bg-white text-center" style="border: thin dotted black;">
                <div class="box-header">  
                
                    <h3 class="text-white"><?php echo $subCategory->sub_category_name ?></h3>
            
                </div> 
            </div>
            </a>
        </div> <!-- div:col-sm-4 -->

        <?php } ?>

    </div> <!-- div:row -->
</div><!-- div:container -->


</div>

views/items/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ItemDetailsModel */

?>
<div class="item-details-model-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'masterItem' => $masterItem,
    ]) ?>

</div>

views/items/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ItemDetailsModel */

$this->title = $model->item_id;
$this->params['breadcrumbs'][] = ['label' => 'Item Details Models', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="item-details-model-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->item_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->item_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'item_id',
            'product_code',
            'restaurant_id',
            'item_name',
            'item_desc',
            'primary_img',
            'primary_cuisine',
            'primary_category',
            'sub_category',
            'price',
            'is_tax_inclusive',
            'item_parcel_charge',
            'is_parcel_tax_applicable',
            'item_status',
            'is_refill_item',
            'is_veg',
            'is_customizable',
            'is_todays_special',
            'serving_time_slots',
            'serving_times',
            'available_days',
            'prep_time:datetime',
            'item_tax_code',
            'printer_config_name',
            'img_url_1:url',
            'img_url_2:url',
            'img_url_3:url',
            'tag_1',
            'tag_2',
            'tag_3',
            'item_count',
            'alert_threshold',
            'meta_data',
            'created_date',
            'last_modified_date',
            'last_updated_by',
            'is_website_displayable',
        ],
    ]) ?>

</div>